word_hints = [
    ['dog', 'Man\'s best friend'],
    ['cat', 'Says "meow"'],
    ['house', 'Where you live'],
    ['tree', 'Has leaves and branches'],
    ['car', 'A vehicle with wheels'],
    ['book', 'Contains stories or information'],
    ['banana', 'Yellow fruit'],
    ['computer', 'Electronic device for processing data'],
    ['guitar', 'Musical instrument with strings'],
    ['sun', 'A star at the center of our solar system'],
    ['pizza', 'Popular Italian dish'],
    ['pencil', 'Used for writing or drawing'],
    ['beach', 'Sandy shore by the ocean'],
    ['moon', 'Earth\'s natural satellite'],
    ['cake', 'Sweet dessert often eaten on birthdays'],
    ['cloud', 'White fluffy mass in the sky'],
    ['bicycle', 'Two-wheeled vehicle'],
    ['phone', 'Device for communication'],
    ['football', 'Sport played with a round ball'],
    ['flower', 'Blooms in gardens'],
    ['bird', 'Has feathers and flies'],
    ['fire', 'Produces heat and light'],
    ['hat', 'Worn on the head for protection or fashion'],
    ['key', 'Used to unlock doors'],
    ['star', 'Shines brightly in the night sky'],
    ['house', 'Where you live'],
    ['chair', 'For sitting on'],
    ['door', 'Allows entry and exit from a room'],
    ['clock', 'Tells time'],
    ['milk', 'White liquid from cows'],
    ['lamp', 'Provides light'],
    ['shoes', 'Worn on the feet'],
    ['table', 'Flat surface for eating or working'],
    ['apple', 'A fruit that is red or green'],
    ['rocket', 'Used to travel to space'],
    ['train', 'Vehicle on tracks'],
    ['river', 'Flows with water'],
    ['moon', 'Earth\'s natural satellite'],
    ['snowman', 'Built with three balls of snow'],
    ['cookie', 'Sweet baked treat'],
    ['umbrella', 'Protects from rain'],
    ['fish', 'Swims in water'],
    ['bird', 'Has feathers and flies'],
    ['flag', 'Symbol of a country'],
    ['butterfly', 'Has colorful wings'],
    ['television', 'Shows images and sound'],
    ['globe', 'Representation of Earth'],
    ['map', 'Shows geographical features'],
    ['glasses', 'Worn to improve vision'],
    ['tiger', 'Large striped cat'],
    ['bottle', 'Container for liquids'],
    ['snake', 'Long reptile'],
    ['moon', 'Earth\'s natural satellite'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['cake', 'Sweet dessert often eaten on birthdays'],
    ['candle', 'Lit for illumination or celebration'],
    ['map', 'Shows geographical features'],
    ['penguin', 'Black and white bird'],
    ['duck', 'Quacks and swims in ponds'],
    ['jungle', 'Thick forest with dense vegetation'],
    ['rainbow', 'Colorful arc in the sky'],
    ['castle', 'Medieval fortress'],
    ['kite', 'Flies in the sky'],
    ['ghost', 'Spirit of a deceased person'],
    ['moon', 'Earth\'s natural satellite'],
    ['train', 'Vehicle on tracks'],
    ['mountain', 'Tall landform'],
    ['guitar', 'Musical instrument with strings'],
    ['crab', 'Walks sideways'],
    ['starfish', 'Sea creature with five arms'],
    ['carrot', 'Orange vegetable'],
    ['crown', 'Worn by royalty'],
    ['bee', 'Produces honey'],
    ['clock', 'Tells time'],
    ['snowflake', 'Falls from the sky in winter'],
    ['robot', 'Mechanical device that can perform tasks'],
    ['ocean', 'Vast body of water'],
    ['frog', 'Amphibian that croaks'],
    ['plane', 'Flies in the sky'],
    ['sunglasses', 'Worn to protect eyes from the sun'],
    ['butterfly', 'Has colorful wings'],
    ['piano', 'Musical instrument with keys'],
    ['helicopter', 'Flies in the air with rotating blades'],
    ['dragon', 'Mythical creature with scales and wings'],
    ['moon', 'Earth\'s natural satellite'],
    ['puzzle', 'Game with pieces that fit together'],
    ['rocket', 'Used to travel to space'],
    ['candy', 'Sweet treat'],
    ['tent', 'Temporary shelter for camping'],
    ['planet', 'Large celestial body that orbits a star'],
    ['spider', 'Has eight legs'],
    ['volcano', 'Erupts with lava and ash'],
    ['diamond', 'Precious gemstone'],
    ['island', 'Landmass surrounded by water'],
    ['magnet', 'Attracts metal'],
    ['apple', 'A fruit that is red or green'],
    ['giraffe', 'Tall African mammal with a long neck'],
    ['train', 'Vehicle on tracks'],
    ['flowerpot', 'Container for plants'],
    ['pineapple', 'Tropical fruit with a spiky skin'],
    ['cupcake', 'Miniature cake'],
    ['butterfly', 'Has colorful wings'],
    ['cactus', 'Has spines and stores water'],
    ['helmet', 'Protects the head'],
    ['sailboat', 'Uses wind to propel on water'],
    ['rocket', 'Used to travel to space'],
    ['penguin', 'Black and white bird'],
    ['banana', 'Yellow fruit'],
    ['tiger', 'Large striped cat'],
    ['pumpkin', 'Orange squash often carved at Halloween'],
    ['zoo', 'Place where animals are kept for public viewing'],
    ['pizza', 'Popular Italian dish'],
    ['robot', 'Mechanical device that can perform tasks'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['ghost', 'Spirit of a deceased person'],
    ['crab', 'Walks sideways'],
    ['tornado', 'Violent rotating column of air'],
    ['butterfly', 'Has colorful wings'],
    ['globe', 'Representation of Earth'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['snowman', 'Built with three balls of snow'],
    ['soccer', 'Sport played with a round ball'],
    ['mountain', 'Tall landform'],
    ['cow', 'Produces milk'],
    ['snail', 'Slow-moving mollusk with a spiral shell'],
    ['jellyfish', 'Has a gelatinous body and stinging tentacles'],
    ['diamond', 'Precious gemstone'],
    ['sandcastle', 'Structure built with sand on the beach'],
    ['penguin', 'Black and white bird'],
    ['camera', 'Device for capturing images'],
    ['bat', 'Flies at night'],
    ['guitar', 'Musical instrument with strings'],
    ['rainbow', 'Colorful arc in the sky'],
    ['mushroom', 'Fungi with a stalk and cap'],
    ['owl', 'Nocturnal bird of prey'],
    ['ice cream', 'Frozen dessert'],
    ['volcano', 'Erupts with lava and ash'],
    ['sunshine', 'Bright light from the sun'],
    ['sandwich', 'Layers of bread with filling'],
    ['elephant', 'Large mammal with a trunk'],
    ['bicycle', 'Two-wheeled vehicle'],
    ['snowball', 'Round mass of snow'],
    ['dragonfly', 'Insect with transparent wings'],
    ['fireworks', 'Explosive pyrotechnic display'],
    ['raincoat', 'Worn to protect from rain'],
    ['ballet', 'Dance form with graceful movements'],
    ['coconut', 'Tropical fruit with a hard shell'],
    ['mermaid', 'Half-human, half-fish mythical creature'],
    ['astronaut', 'Person who travels to space'],
    ['unicorn', 'Mythical horse with a horn on its forehead'],
    ['wizard', 'Magical practitioner'],
    ['dolphin', 'Marine mammal known for its intelligence'],
    ['penguin', 'Black and white bird'],
    ['jigsaw', 'Puzzle with interlocking pieces'],
    ['telescope', 'Instrument for viewing distant objects'],
    ['caterpillar', 'Larval stage of a butterfly or moth'],
    ['carousel', 'Merry-go-round'],
    ['firefighter', 'Person who extinguishes fires'],
    ['ladybug', 'Small beetle with red and black spots'],
    ['sandcastle', 'Structure built with sand on the beach'],
    ['birthday', 'Celebration of one\'s date of birth'],
    ['campfire', 'Outdoor fire for warmth or cooking'],
    ['rainforest', 'Lush forest with heavy rainfall'],
    ['popcorn', 'Popped corn kernels'],
    ['parrot', 'Colorful bird that can mimic speech'],
    ['submarine', 'Underwater vessel'],
    ['toothbrush', 'Used for cleaning teeth'],
    ['hamburger', 'Ground meat patty in a bun'],
    ['toucan', 'Colorful bird with a large beak'],
    ['skyscraper', 'Tall building with many floors'],
    ['watermelon', 'Large fruit with juicy red flesh'],
    ['tornado', 'Violent rotating column of air'],
    ['kangaroo', 'Marsupial from Australia'],
    ['sunglasses', 'Worn to protect eyes from the sun'],
    ['strawberry', 'Small red fruit'],
    ['hot air balloon', 'Aircraft lifted by heated air'],
    ['pirate', 'Seafaring robber'],
    ['earthquake', 'Sudden shaking of the ground'],
    ['cactus', 'Has spines and stores water'],
    ['snowflake', 'Falls from the sky in winter'],
    ['dragon', 'Mythical creature with scales and wings'],
    ['snowboard', 'Used for gliding downhill on snow'],
    ['waterfall', 'Flowing water over a cliff'],
    ['carnival', 'Festive fair with rides and games'],
    ['cheeseburger', 'Hamburger with cheese on top'],
    ['raindrop', 'Falls from the sky when it rains'],
    ['carousel', 'Merry-go-round'],
    ['football', 'Sport played with a round ball'],
    ['umbrella', 'Used to shield from rain or sun'],
    ['chocolate', 'Sweet treat made from cocoa beans'],
    ['penguin', 'Black and white bird'],
    ['teddy bear', 'Soft toy in the shape of a bear'],
    ['astronaut', 'Person who travels to space'],
    ['roller coaster', 'Amusement park ride with twists and turns'],
    ['scarecrow', 'Keeps birds away from crops'],
    ['watermelon', 'Large fruit with juicy red flesh'],
    ['sweater', 'Worn to keep warm in cold weather'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['snowman', 'Figure made of packed snow'],
    ['snorkeling', 'Swimming underwater with a breathing tube'],
    ['spaceship', 'Vehicle for traveling in outer space'],
    ['squirrel', 'Small mammal with a bushy tail'],
    ['backpack', 'Carried on the back for holding belongings'],
    ['ballet', 'Dance form with graceful movements'],
    ['lemonade', 'Citrus-flavored drink'],
    ['lollipop', 'Sweet candy on a stick'],
    ['hurricane', 'Powerful tropical cyclone'],
    ['teddy bear', 'Soft toy in the shape of a bear'],
    ['mailbox', 'Used for sending and receiving mail'],
    ['stargazing', 'Observing celestial objects in the night sky'],
    ['hot chocolate', 'Warm drink made from cocoa'],
    ['snowflake', 'Falls from the sky in winter'],
    ['sailboat', 'Boat propelled by sails'],
    ['telescope', 'Instrument for viewing distant objects'],
    ['popcorn', 'Popped corn kernels'],
    ['kayaking', 'Paddling in a small boat'],
    ['tugboat', 'Small boat used for towing larger vessels'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['whale', 'Large marine mammal'],
    ['cherry', 'Small fruit with a pit'],
    ['backpack', 'Carried on the back for holding belongings'],
    ['sushi', 'Japanese dish with rice and seafood'],
    ['pineapple', 'Tropical fruit with a spiky skin'],
    ['puzzle', 'Game with pieces that fit together'],
    ['cruise ship', 'Large vessel for leisure travel on water'],
    ['treasure', 'Hidden riches or valuable items'],
    ['raincoat', 'Worn to protect from rain'],
    ['fireplace', 'Where you can have a cozy fire'],
    ['baseball', 'Sport played with a bat and ball'],
    ['picnic', 'Outdoor meal'],
    ['giraffe', 'Tall African mammal with a long neck'],
    ['campfire', 'Outdoor fire for warmth or cooking'],
    ['snowboard', 'Used for gliding downhill on snow'],
    ['jellyfish', 'Has a gelatinous body and stinging tentacles'],
    ['toothpaste', 'Used for cleaning teeth'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['tornado', 'Violent rotating column of air'],
    ['karaoke', 'Singing along to recorded music'],
    ['dragonfly', 'Insect with transparent wings'],
    ['hot air balloon', 'Aircraft lifted by heated air'],
    ['hiking', 'Walking in nature'],
    ['volcano', 'Erupts with lava and ash'],
    ['parachute', 'Used for safely descending from an aircraft'],
    ['caterpillar', 'Larval stage of a butterfly or moth'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['waterfall', 'Flowing water over a cliff'],
    ['carnival', 'Festive fair with rides and games'],
    ['cheeseburger', 'Hamburger with cheese on top'],
    ['raindrop', 'Falls from the sky when it rains'],
    ['carousel', 'Merry-go-round'],
    ['football', 'Sport played with a round ball'],
    ['umbrella', 'Used to shield from rain or sun'],
    ['chocolate', 'Sweet treat made from cocoa beans'],
    ['penguin', 'Black and white bird'],
    ['teddy bear', 'Soft toy in the shape of a bear'],
    ['astronaut', 'Person who travels to space'],
    ['roller coaster', 'Amusement park ride with twists and turns'],
    ['scarecrow', 'Keeps birds away from crops'],
    ['watermelon', 'Large fruit with juicy red flesh'],
    ['sweater', 'Worn to keep warm in cold weather'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['snowman', 'Figure made of packed snow'],
    ['snorkeling', 'Swimming underwater with a breathing tube'],
    ['spaceship', 'Vehicle for traveling in outer space'],
    ['squirrel', 'Small mammal with a bushy tail'],
    ['backpack', 'Carried on the back for holding belongings'],
    ['ballet', 'Dance form with graceful movements'],
    ['lemonade', 'Citrus-flavored drink'],
    ['lollipop', 'Sweet candy on a stick'],
    ['hurricane', 'Powerful tropical cyclone'],
    ['teddy bear', 'Soft toy in the shape of a bear'],
    ['mailbox', 'Used for sending and receiving mail'],
    ['stargazing', 'Observing celestial objects in the night sky'],
    ['hot chocolate', 'Warm drink made from cocoa'],
    ['snowflake', 'Falls from the sky in winter'],
    ['sailboat', 'Boat propelled by sails'],
    ['telescope', 'Instrument for viewing distant objects'],
    ['popcorn', 'Popped corn kernels'],
    ['kayaking', 'Paddling in a small boat'],
    ['tugboat', 'Small boat used for towing larger vessels'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['whale', 'Large marine mammal'],
    ['cherry', 'Small fruit with a pit'],
    ['backpack', 'Carried on the back for holding belongings'],
    ['sushi', 'Japanese dish with rice and seafood'],
    ['pineapple', 'Tropical fruit with a spiky skin'],
    ['puzzle', 'Game with pieces that fit together'],
    ['cruise ship', 'Large vessel for leisure travel on water'],
    ['treasure', 'Hidden riches or valuable items'],
    ['raincoat', 'Worn to protect from rain'],
    ['fireplace', 'Where you can have a cozy fire'],
    ['baseball', 'Sport played with a bat and ball'],
    ['picnic', 'Outdoor meal'],
    ['giraffe', 'Tall African mammal with a long neck'],
    ['campfire', 'Outdoor fire for warmth or cooking'],
    ['snowboard', 'Used for gliding downhill on snow'],
    ['jellyfish', 'Has a gelatinous body and stinging tentacles'],
    ['toothpaste', 'Used for cleaning teeth'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['tornado', 'Violent rotating column of air'],
    ['karaoke', 'Singing along to recorded music'],
    ['dragonfly', 'Insect with transparent wings'],
    ['hot air balloon', 'Aircraft lifted by heated air'],
    ['hiking', 'Walking in nature'],
    ['volcano', 'Erupts with lava and ash'],
    ['parachute', 'Used for safely descending from an aircraft'],
    ['caterpillar', 'Larval stage of a butterfly or moth'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['Apple', 'Red, round fruit'],
    ['Banana', 'Curved, yellow fruit'],
    ['Orange', 'Citrus fruit, rhymes with "door hinge"'],
    ['Grape', 'Small, round fruit that grows in clusters'],
    ['Strawberry', 'Red, sweet fruit with a leafy top'],
    ['Pineapple', 'Spiky, tropical fruit'],
    ['Watermelon', 'Large, green fruit with red or yellow flesh'],
    ['Lemon', 'Yellow citrus fruit, sour taste'],
    ['Pear', 'Bell-shaped fruit, sweet or tart'],
    ['Peach', 'Fuzzy-skinned fruit with a stone pit'],

    ['House', 'Building you live in'],
    ['Tree', 'Tall plant with trunk and branches'],
    ['Flower', 'Blooming part of a plant'],
    ['Car', 'Vehicle with wheels and engine'],
    ['Bicycle', 'Two-wheeled vehicle powered by pedals'],
    ['Motorcycle', 'Two-wheeled vehicle with an engine'],
    ['Airplane', 'Flies through the air, has wings'],
    ['Boat', 'Floats on water, used for transportation'],
    ['Train', 'Series of connected cars, travels on tracks'],
    ['Bus', 'Large vehicle that carries passengers'],

    ['Cat', 'Fluffy pet with whiskers'],
    ['Dog', 'Loyal pet, barks and wags its tail'],
    ['Bird', 'Has feathers and wings, can fly'],
    ['Fish', 'Lives in water, has gills to breathe'],
    ['Snake', 'Long, slender reptile without legs'],
    ['Insect', 'Small, six-legged creature'],
    ['Spider', 'Eight-legged creature that spins webs'],
    ['Butterfly', 'Beautiful insect with colorful wings'],
    ['Turtle', 'Reptile with a hard shell'],
    ['Horse', 'Large mammal with long mane and tail'],

    ['Book', 'Has pages with information or stories'],
    ['Computer', 'Electronic device for work or entertainment'],
    ['Phone', 'Used for communication, can be a landline or mobile'],
    ['Television', 'Shows movies and programs'],
    ['Radio', 'Receives audio broadcasts'],
    ['Camera', 'Takes pictures'],
    ['Guitar', 'String instrument played with fingers or a pick'],
    ['Piano', 'Keyboard instrument with black and white keys'],
    ['Drum', 'Percussion instrument played with sticks'],
    ['Violin', 'String instrument played with a bow'],

    ['Sun', 'Light, hot'],
    ['Moon', 'Night, round'],
    ['Star', 'Sky, shines'],
    ['Cloud', 'Fluffy, rain'],
    ['Rainbow', 'Colors, after rain'],
    ['Lightning', 'Flash, thunder'],
    ['Fire', 'Hot, burns'],
    ['Water', 'Drinks, ocean'],
    ['Mountain', 'Tall, peak'],
    ['River', 'Flows, water'],

    ['Face', 'Eyes, nose'],
    ['Hand', 'Fingers'],
    ['Arm', 'Body part'],
    ['Leg', 'Walks'],
    ['Foot', 'Shoe'],
    ['Head', 'Hair'],
    ['Eye', 'Sees'],
    ['Ear', 'Hears'],
    ['Nose', 'Smells'],
    ['Mouth', 'Talks, eats'],

    ['Shirt', 'Clothes'],
    ['Pants', 'Clothes, legs'],
    ['Dress', 'Clothes'],
    ['Shoes', 'Feet'],
    ['Hat', 'Head'],
    ['Glasses', 'Eyes'],
    ['Table', 'Flat surface'],
    ['Chair', 'Seat'],
    ['Bed', 'Sleep'],
    ['Couch', 'Sit, relax'],

    ['Kitchen', 'Cooking'],
    ['Bathroom', 'Shower'],
    ['Bedroom', 'Sleep'],
    ['Living room', 'Relax'],
    ['School', 'Learn'],
    ['Hospital', 'Doctors'],
    ['Restaurant', 'Eat out'],
    ['Park', 'Play outside'],
    ['Beach', 'Sand, ocean'],
    ['Forest', 'Trees'],

    ['Happy', 'Smiling'],
    ['Sad', 'Crying'],
    ['Angry', 'Frowning'],
    ['Scared', 'Wide eyes'],
    ['Surprised', 'Open mouth'],
    ['Love', 'Heart'],
    ['Hate', 'Angry face'],
    ['Hungry', 'Eating'],
    ['Thirsty', 'Drinking'],
    ['Tired', 'Sleeping'],
    ['butterfly', 'Has colorful wings'],
    ['caterpillar', 'Larval stage of a butterfly or moth'],
    ['hurricane', 'Powerful tropical cyclone'],
    ['lightning', 'Electric discharge in the atmosphere'],
    ['carousel', 'Merry-go-round'],
    ['carousel', 'Merry-go-round'],
    ['rainforest', 'Lush forest with heavy rainfall'],
    ['bouquet', 'Arrangement of flowers'],
    ['volleyball', 'Sport played with a ball over a net'],
    ['dragonfly', 'Insect with transparent wings'],
    ['spaceship', 'Vehicle for traveling in outer space'],
    ['squirrel', 'Small mammal with a bushy tail'],
    ['zookeeper', 'Person who cares for animals in a zoo'],
    ['compass', 'Navigational instrument'],
    ['backpack', 'Carried on the back for holding belongings'],
    ['seashell', 'Shell found on beaches'],
    ['campfire', 'Outdoor fire for warmth or cooking'],
    ['binoculars', 'Optical device for viewing distant objects'],
    ['flashlight', 'Portable electric light'],
    ['sunglasses', 'Worn to protect eyes from the sun'],
    ['chameleon', 'Lizard capable of changing color'],
    ['skyscraper', 'Tall building with many floors'],
    ['acorn', 'Nut of an oak tree'],
    ['sunrise', 'When the sun comes up in the morning'],
    ['waterfall', 'Flowing water over a cliff'],
    ['toucan', 'Colorful bird with a large beak'],
    ['snowball', 'Round mass of snow'],
    ['binoculars', 'Optical device for viewing distant objects'],
    ['whirlpool', 'Swirling body of water'],
    ['spaceship', 'Vehicle for traveling in outer space'],
    ['cinnamon', 'Spice made from tree bark'],
    ['orchard', 'Area of land where fruit trees are grown'],
    ['sundial', 'Clock that uses the position of the sun'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['dragonfly', 'Insect with transparent wings'],
    ['tornado', 'Violent rotating column of air'],
    ['seesaw', 'Playground equipment for two people'],
    ['nightingale', 'Small bird known for its melodious song'],
    ['raincoat', 'Worn to protect from rain'],
    ['garden', 'Outdoor space for growing plants'],
    ['backpack', 'Carried on the back for holding belongings'],
    ['jigsaw', 'Puzzle with interlocking pieces'],
    ['sunset', 'When the sun goes down in the evening'],
    ['picnic', 'Outdoor meal'],
    ['mountaintop', 'Peak of a mountain'],
    ['telescope', 'Instrument for viewing distant objects'],
    ['watermelon', 'Large fruit with juicy red flesh'],
    ['sweater', 'Worn to keep warm in cold weather'],
    ['snowman', 'Figure made of packed snow'],
    ['snorkeling', 'Swimming underwater with a breathing tube'],
    ['cruise', 'Leisure trip on a ship'],
    ['tugboat', 'Small boat used for towing larger vessels'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['whale', 'Large marine mammal'],
    ['cherry', 'Small fruit with a pit'],
    ['sushi', 'Japanese dish with rice and seafood'],
    ['pineapple', 'Tropical fruit with a spiky skin'],
    ['puzzle', 'Game with pieces that fit together'],
    ['treasure', 'Hidden riches or valuable items'],
    ['raincoat', 'Worn to protect from rain'],
    ['fireplace', 'Where you can have a cozy fire'],
    ['baseball', 'Sport played with a bat and ball'],
    ['picnic', 'Outdoor meal'],
    ['giraffe', 'Tall African mammal with a long neck'],
    ['campfire', 'Outdoor fire for warmth or cooking'],
    ['snowboard', 'Used for gliding downhill on snow'],
    ['jellyfish', 'Has a gelatinous body and stinging tentacles'],
    ['toothpaste', 'Used for cleaning teeth'],
    ['lighthouse', 'Tower with a light to guide ships at sea'],
    ['tornado', 'Violent rotating column of air'],
    ['karaoke', 'Singing along to recorded music'],
    ['dragonfly', 'Insect with transparent wings'],
    ['hot air balloon', 'Aircraft lifted by heated air'],
    ['hiking', 'Walking in nature'],
    ['volcano', 'Erupts with lava and ash'],
    ['parachute', 'Used for safely descending from an aircraft'],
    ['caterpillar', 'Larval stage of a butterfly or moth'],
    ['sunflower', 'Yellow flower that follows the sun'],
    ['airplane', 'Flying vehicle powered by engines'],
    ['basketball', 'Sport played with a ball and hoop'],
    ['castle', 'Fortified building usually with towers and a moat'],
    ['detective', 'Person who solves crimes'],
    ['elephant', 'Large mammal with a trunk and tusks'],
    ['fairy', 'Mythical creature with magical powers'],
    ['garden', 'Outdoor space for growing plants'],
    ['hospital', 'Place for medical treatment and care'],
    ['island', 'Landmass surrounded by water'],
    ['jungle', 'Thick tropical forest'],
    ['kangaroo', 'Marsupial native to Australia'],
    ['lemon', 'Yellow citrus fruit with sour taste'],
    ['mountain', 'High landmass with steep sides'],
    ['notebook', 'Bound pad of paper for writing'],
    ['ocean', 'Vast body of saltwater'],
    ['puzzle', 'Game or toy that tests one\'s ingenuity'],
    ['queen', 'Female ruler of a kingdom'],
    ['rainbow', 'Multicolored arc in the sky'],
    ['sailboat', 'Boat propelled by wind'],
    ['tiger', 'Large carnivorous feline with stripes'],
    ['umbrella', 'Canopy used to protect from rain or sun'],
    ['volcano', 'Mountain that erupts with lava and ash'],
    ['whale', 'Large marine mammal'],
    ['xylophone', 'Musical instrument with wooden bars'],
    ['yacht', 'Luxury boat for pleasure cruising'],
    ['zebra', 'Striped African mammal'],
    ['astronaut', 'Person who travels in space'],
    ['butterfly', 'Insect with colorful wings'],
    ['candle', 'Wax stick with a wick that burns'],
    ['dinosaur', 'Extinct reptile from prehistoric times'],
    ['eclipse', 'Obscuring of one celestial body by another'],
    ['firefighter', 'Person who extinguishes fires'],
    ['giraffe', 'Tall African mammal with long neck'],
    ['helicopter', 'Aircraft with rotating blades for lift'],
    ['igloo', 'Dome-shaped shelter made of ice'],
    ['jockey', 'Rider in horse races'],
    ['koala', 'Australian marsupial with grey fur'],
    ['lighthouse', 'Tower with a bright light for navigation'],
    ['mushroom', 'Fleshy fungus with a stalk and cap'],
    ['ninja', 'Japanese warrior skilled in martial arts'],
    ['octopus', 'Eight-armed marine mollusk'],
    ['penguin', 'Flightless bird native to Antarctica'],
    ['quicksand', 'Loose wet sand that sucks in objects'],
    ['raincoat', 'Waterproof garment worn in rain'],
    ['spaceship', 'Vehicle for travel in outer space'],
    ['tornado', 'Violent swirling column of air'],
    ['unicorn', 'Mythical horse with a single horn'],
    ['volleyball', 'Sport played with a ball over a net'],
    ['waterfall', 'Cascade of water flowing over a cliff'],
    ['xylophone', 'Musical instrument with wooden bars'],
    ['yoga', 'Physical and mental exercise for well-being'],
    ['zeppelin', 'Type of airship used for transport'],
    ['acrobat', 'Person who performs gymnastic feats'],
    ['bicycle', 'Two-wheeled vehicle powered by pedaling'],
    ['clown', 'Entertainer known for humorous antics'],
    ['dolphin', 'Intelligent aquatic mammal with fins'],
    ['elephant', 'Large mammal with a trunk and tusks'],
    ['fireworks', 'Explosive devices for celebration'],
    ['guitar', 'Stringed instrument with a fretted neck'],
    ['hurricane', 'Intense tropical cyclone with strong winds'],
    ['igloo', 'Dome-shaped shelter made of ice'],
    ['jungle', 'Tropical forest with dense vegetation'],
    ['kite', 'Toy flown in the wind on a string'],
    ['lighthouse', 'Tall tower with a bright light for navigation'],
    ['moon', 'Natural satellite of the Earth'],
    ['nest', 'Structure built by birds for laying eggs'],
    ['octopus', 'Eight-armed marine mollusk'],
    ['palm', 'Tree with a straight trunk and large leaves'],
    ['quill', 'Feather used as a writing instrument'],
    ['rainbow', 'Multicolored arc in the sky'],
    ['seahorse', 'Small marine fish with a curled tail'],
    ['tornado', 'Violently rotating column of air'],
    ['unicorn', 'Mythical horse with a single horn'],
    ['volcano', 'Mountain that erupts with lava and ash'],
    ['whale', 'Large marine mammal'],
    ['xylophone', 'Musical instrument with wooden bars'],
    ['yacht', 'Luxury boat for pleasure cruising'],
    ['zebra', 'Striped African mammal']
]
